name: new_boilerplate
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  cupertino_icons: ^1.0.5
  dio: ^5.1.1
  flutter_facebook_auth: ^5.0.8
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  headup_loading: ^1.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_gallery_saver: ^1.7.1
  image_picker: ^0.8.7+2
  in_app_update: ^4.0.1
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.3+1
  line_icons: ^2.0.1
  onesignal_flutter: ^3.5.1
  package_info: ^2.0.2
  page_transition: ^2.0.9
  path_provider: ^2.0.14
  photo_view: ^0.14.0
  platform_device_id: ^1.0.1
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  responsive_framework: ^0.2.0
  shimmer: ^2.0.0
  simple_animations: ^5.0.0+3
  sms_autofill: ^2.3.0
  sqflite: ^2.2.6
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.7

dependency_overrides:
  intl: ">=0.17.0"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - google_fonts/
    - assets/

  fonts:
    - family: JeteIcon
      fonts:
        - asset: assets/icons/JeteIcon.ttf
    - family: MaisonNeue
      fonts:
        - asset: assets/fonts/MaisonNeue-Book.otf
